---
title: "ploidy_snp_props_simulation"
author: "Florian"
date: "`r Sys.Date()`"
output: html_document
---


# Simulation of read_allele_proportions


```{r}
# Function to simulate allele proportions for a single SNP
simulate_snp <- function(mean_depth, n_sites, ploidy, biallelic_freqs,freqs_prob) {
  # Sample read depth from exponential distribution
  read_depth <- round(rexp(1, rate = 1/mean_depth), 0)
  
  # Sample biallelic frequency state based on ploidy
  biallelic_state <- sample(1:length(biallelic_freqs), size = 1, prob = freqs_prob)
  #print("START")

  # Extract corresponding biallelic frequencies
  freq_a <- biallelic_freqs[[biallelic_state]][1]
  freq_b <- biallelic_freqs[[biallelic_state]][2]
  

  # Sample alleles based on frequencies
  alleles <- sample(c("A", "B"), size = read_depth, prob = c(freq_a, freq_b), replace = TRUE)
  
  alleles_a <- sum(alleles == "A")
  alleles_b <- sum(alleles == "B")
  
  # Estimate allele proportions
  prop_a <- alleles_a / read_depth
  prop_b <- alleles_b / read_depth
  
  #print(alleles)
  #print(c(prop_a, prop_b))
  
  # Return allele proportions
  return(c(read_depth,alleles_a,alleles_b,prop_a, prop_b))
}

# Define biallelic frequencies for different ploidies
biallelic_freqs_diploid <- list(c(0.5, 0.5))
biallelic_freqs_triploid <- list(c(0.33, 0.66))
biallelic_freqs_tetraploid <- list(c(0.5,0.5),c(0.25, 0.75))

# Set parameters
mean_depth <- 20  # Adjust this value as needed
n_sites <- 10000    # Adjust this value as needed

# Define ploidies to simulate
ploidies <- c(2, 3, 4)

# Select ploidy randomly
current_ploidy <- sample(ploidies, size = 1)
current_ploidy <- 4
# Get corresponding biallelic frequencies
if (current_ploidy == 2) {
  biallelic_freqs <- biallelic_freqs_diploid
  freqs_prob <- 1
} else if (current_ploidy == 3) {
  biallelic_freqs <- biallelic_freqs_triploid
  freqs_prob <- 1
} else if (current_ploidy == 4){
  biallelic_freqs <- biallelic_freqs_tetraploid
  freqs_prob <- c(0.25,0.75)
}

print(current_ploidy)
# Initialize empty matrix to store allele proportions
#all_props <- matrix(nrow = n_sites, ncol = 5)
all_props <- data.frame()

# Simulate for each SNP site
for (i in 1:n_sites) {
  
  # Simulate and store allele proportions
  props <- simulate_snp(mean_depth, 1, current_ploidy, biallelic_freqs,freqs_prob)
  #all_props[i, ] <- props
  all_props <- rbind(all_props,props)
}

colnames(all_props) <- c("read_depth","allele_a_reads","allele_b_reads","allele_prop_a","allele_prop_b")

# Print or further analyze the simulated allele proportions in all_props matrix
#print(all_props)

```




# QC filtering and plotting


```{r}
minimum_allele_depth <- 5

all_props_QC <-all_props[all_props$allele_a_reads >= minimum_allele_depth & all_props$allele_b_reads >= minimum_allele_depth,]
```



```{r}
library(ggplot2)

complete_freqs <- c(all_props_QC$allele_prop_a,all_props_QC$allele_prop_b) 

ggplot(as.data.frame(complete_freqs), aes(x = complete_freqs)) +
  geom_histogram(alpha = 0.5, fill = "blue", binwidth = 0.001) +  # Adjust bins as needed
  labs(title = "Distribution of Two Columns", x = "biallelic_frequency") +
  xlim(0,1)
```



```{r}
library(ggplot2)

ggplot(all_props_QC, aes(x = allele_prop_a)) +
  geom_histogram(alpha = 0.5, fill = "blue", binwidth = 0.01) +  # Adjust bins as needed
  geom_histogram(data = all_props_QC, aes(x = allele_prop_b), alpha = 0.5, fill = "red", binwidth = 0.01) +
  labs(title = "Distribution of Two Columns", x = "Values")
```

